config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :articlesы
  end

  resources :likes, only: [:create, :destroy]

  devise_for :users

  root 'welcome#index'
  get 'welcome/index', as: 'user_root'
  get 'tag/:id', to: 'welcome#tag', as: 'tag'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
    user ||= User.new # guest user (not logged in)

    if user.id == 1
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user, foreign_key: "author_id"
  has_many :articles_to_tags
  has_many :tags, :through => :articles_to_tags
  has_many :likes
  has_many :users, :through => :likes
end

app/models/articles_to_tag.rb
class ArticlesToTag < ActiveRecord::Base
  belongs_to :article
  belongs_to :tag
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :article

end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, foreign_key: "author_id"
  has_many :likes
  has_many :articles, :through => :likes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  def index
    @articles = Article.all
    authorize! :manage, @articles
  end

  def create
    authorize! :manage, :create
    Article.create(article_params())
    redirect_to admin_articles_path
  end

  def new
    authorize! :manage, :new
    @article = Article.new
  end

  def show
    @article = Article.find(params[:id])
    authorize! :manage, @article
  end

  def edit
    @article = Article.find(params[:id])
    authorize! :manage, @article
  end

  def update
    article = Article.find(params[:id])
    authorize! :manage, article
    article.update!(article_params())
    redirect_to edit_admin_article_path(params[:id])
  end

  def destroy
    article = Article.find(params[:id])
    authorize! :manage, article
    article.destroy
    redirect_to admin_articles_path
  end

  private
    def article_params
      params.require(:article).permit(:name, :text)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale
  before_filter :authenticate_user!

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def after_sign_in_path_for(resource)
    user_root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    like = Like.new
    like.article_id = params[:article_id]
    like.user_id = current_user.id
    like.save
    head :no_content
  end

  def destroy
    like = Like.find_by(article_id: params[:article_id], user_id: current_user.id)
    like.destroy
    head :no_content
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    page = (params[:page].blank?) ? 1 : Integer(params[:page])
    per_page = 1
    @articles = Article.joins("LEFT JOIN likes ON articles.id = likes.article_id AND likes.user_id = #{current_user.id}").limit(per_page).offset((page - 1) * per_page)
    @articles_paginate = Article.paginate(:page => params[:page], :per_page => per_page)
  end

  def tag
    @articles = Article.joins(:articles_to_tags).where('articles_to_tags.tag_id' => params[:id])
    render :index
  end
end

app/helpers/likes_helper.rb
module LikesHelper
  def set_class_liked(article)
    if article.likes.blank?
      'like'
    else
      'like liked'
    end
  end
end

app/views/admin/articles/create.html.erb
<h1>Admin::Articles#create</h1>
<p>Find me in app/views/admin/articles/create.html.erb</p>

app/views/admin/articles/destroy.html.erb
<h1>Admin::Articles#destroy</h1>
<p>Find me in app/views/admin/articles/destroy.html.erb</p>

app/views/admin/articles/edit.html.erb
<div class="list-articles">
  <div class="panel panel-default">
    <div class="panel-heading">

    </div>
    <div class="panel-body">
      <%= form_for [:admin, @article] do |f| %>
          <div class="form-group">
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.text_area :text, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.submit I18n.t("manage.save"), class: "btn btn-default" %>
          </div>
      <% end %>
    </div>
    <div class="panel-footer">

    </div>
  </div>
</div>

app/views/admin/articles/index.html.erb
<div class="list-articles">
  <%= link_to(I18n.t("manage.create"), new_admin_article_path) %>
  <div class="list-group">
    <% @articles.each do |article| %>
        <%= link_to(article.name, admin_article_path(article), class: "list-group-item") %>
    <% end %>
  </div>
</div>

app/views/admin/articles/new.html.erb
<div class="list-articles">
  <div class="panel panel-default">
    <div class="panel-heading">

    </div>
    <div class="panel-body">
      <%= form_for [:admin, @article] do |f| %>
        <div class="form-group">
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.text_area :text, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit I18n.t("manage.create"), class: "btn btn-default" %>
        </div>
      <% end %>
    </div>
    <div class="panel-footer">

    </div>
  </div>
</div>

app/views/admin/articles/show.html.erb
<div class="list-articles">
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= link_to(I18n.t("manage.edit"), edit_admin_article_path(@article)) %>
        |
        <%= link_to(I18n.t("manage.delete"), admin_article_path(@article), method: :delete) %>
        |
        <%= @article.name %>
      </div>
      <div class="panel-body">
        <%= @article.text %>
      </div>
      <div class="panel-footer">
        <%=t :tags %>
        <% @article.tags.each do |tag| %>
            <%= link_to(tag_path(tag.id)) do %>
                <span class="label label-info"><%= tag.name %></span>
            <% end %>
        <% end %>
      </div>
    </div>
</div>

app/views/admin/articles/update.html.erb
<h1>Admin::Articles#update</h1>
<p>Find me in app/views/admin/articles/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ruby</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'partials/navigation' %>
  <%= yield %>
</body>
</html>

app/views/partials/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <p class="navbar-text"><%= link_to "NoveoBlog", user_root_path %> </p>
      <p>
        <%= link_to "en", params.merge(:locale => "en") %>
        /
        <%= link_to "ru", params.merge(:locale => "ru") %>
      </p>
    </div>
    <div class="navbar-collapse collapse">
      <% if user_signed_in? %>
          <p class="navbar-text navbar-right"><%= link_to I18n.t('header.logout'), destroy_user_session_path, :method => :delete, class: "navbar-link" %></p>
          <p class="navbar-text navbar-right"><%=t 'header.signed_as' %> <a href="#" class="navbar-link"><%= current_user.email %></a></p>
          <% if can? :update, @article %>
              <p class="navbar-text navbar-right">
                <%= link_to(I18n.t("adminbar"), admin_articles_path) %>
              </p>
          <% end %>

      <% else %>
          <p class="navbar-text navbar-right">
            <%= link_to I18n.t('header.login'), new_user_session_path, class: "navbar-link" %>
            /
            <%= link_to I18n.t('header.signin'), new_user_registration_path, class: "navbar-link" %>
          </p>
      <% end %>
    </div>
  </div>
</nav>

app/views/welcome/index.html.erb
<div class="list-articles">
  <% @articles.each do |article| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= link_to('#', class: set_class_liked(article), data: {article_id: article.id}) do %>
            <span class="glyphicon glyphicon-heart"></span>
        <% end %> |
        <%= article.name %>
      </div>
      <div class="panel-body">
        <%= article.text %>
      </div>
      <div class="panel-footer">
        <%=t :tags %>
        <% article.tags.each do |tag| %>
            <%= link_to(tag_path(tag.id)) do %>
              <span class="label label-info"><%= tag.name %></span>
            <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
  <%= will_paginate @articles_paginate %>
</div>

app/views/welcome/tag.erb
<div class="list-articles">
  <% @articles.each do |article| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= article.name %>
        </div>
        <div class="panel-body">
          <%= article.text %>
        </div>
        <div class="panel-footer">
          Теги:
          <% article.tags.each do |tag| %>
              <%= link_to(tag_path(tag.id)) do %>
                  <span class="label label-info"><%= tag.name %></span>
              <% end %>
          <% end %>
        </div>
      </div>
  <% end %>
</div>